window.papersData = [
  {
    "id": 41,
    "title": "Tough and crack-resistant elastomers via balancing interchain interactions and entanglements",
    "authors": "G. Zhang, Y. Zhang, B. Zhao, X. Zheng, B. Wu, Z. Li, Z. Huang, X. Zhan, M. Wang*, X. Xiao*",
    "journal": "Journal of Materials Chemistry A",
    "year": 2026,
    "volume": "14",
    "pages": null,
    "abstract": "...",
    "url": "https://doi.org/10.1039/D6TA04580D",
    "image": "images/paper41-toc.png",
    "citation": "Journal of Materials Chemistry A (2026)",
    "doi": "10.1039/D6TA04580D"
  },
  {
    "id": 42,
    "title": "Functional ionogels: design principles and applications",
    "authors": "R. Wu, J. Zhang, X. Xiao*, M. Wang*",
    "journal": "Chinese Journal of Polymer Science",
    "year": 2026,
    "volume": "44",
    "pages": "1645-1666",
    "abstract": "...",
    "url": "https://www.cjps.org/en/article/doi/10.1007/s10118-026-3584-y/",
    "image": "images/paper42-toc.png",
    "citation": "Chinese Journal of Polymer Science 44, 1645-1666 (2026)",
    "doi": "10.1007/s10118-026-3584-y"
  },
  {
    "id": 1,
    "title": "Aqueous-based recycling of perovskite photovoltaics",
    "authors": "X. Xiao, N. Xu, X. Tian, T. Zhang, B. Wang, X. Wang, Y. Xian, C. Lu, X. Ou, Y. Yan, L. Sun, F. You*, F. Gao*",
    "journal": "Nature",
    "year": 2025,
    "volume": "638",
    "pages": "670-675",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41586-024-08408-7",
    "image": "images/paper1.png",
    "citation": "Nature 638, 670-675 (2025)",
    "doi": "10.1038/s41586-024-08408-7"
  },
  {
    "id": 2,
    "title": "Glassy gels toughened by solvent",
    "authors": "M. Wang#, X. Xiao#, S. Siddika, M. Shamsi, E. Frey, W. Qian, W. Bai, B. T. O'Connor, M. D. Dickey*",
    "journal": "Nature",
    "year": 2024,
    "volume": "631",
    "pages": "313-318",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41586-024-07564-0",
    "image": "images/paper2-toc.png",
    "citation": "Nature 631, 313-318 (2024)",
    "doi": "10.1038/s41586-024-07564-0"
  },
  {
    "id": 3,
    "title": "Lead-adsorbing ionogel-based encapsulation for impact-resistant, stable and lead-safe perovskite modules",
    "authors": "X. Xiao#, M. Wang#, S. Chen, Y. Zhang, H. Gu, Y. Deng, G. Yang, C. Fei, B. Chen, Y. Lin, M. D. Dickey, J. Huang*",
    "journal": "Science Advances",
    "year": 2021,
    "volume": "7",
    "pages": "eabi8249",
    "abstract": "...",
    "url": "https://www.science.org/doi/10.1126/sciadv.abi8249",
    "image": "images/paper3.jpg",
    "citation": "Science Advances 7, eabi8249 (2021)",
    "doi": "10.1126/sciadv.abi8249"
  },
  {
    "id": 4,
    "title": "Layer number dependent ferroelasticity in 2D Ruddlesden-popper organic-inorganic hybrid perovskites",
    "authors": "X. Xiao, J. Zhou, K. Song, J. Zhao, Y. Zhou, P. N. Rudd, Y. Han, J. Li*, J. Huang*",
    "journal": "Nature Communications",
    "year": 2021,
    "volume": 12,
    "pages": "1332",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-021-21493-w",
    "image": "images/paper4-toc.png",
    "citation": "Nature Communications 12, 1332 (2021)",
    "doi": "10.1038/s41467-021-21493-w"
  },
  {
    "id": 5,
    "title": "Benign ferroelastic twin boundaries in halide perovskites for charge carrier transport and recombination",
    "authors": "X. Xiao#, W. Li#, Y. Fang#, Y. Liu, Y. Shao, S. Yang, J. Zhao, X. Dai, R. Zia, J. Huang*",
    "journal": "Nature Communications",
    "year": 2020,
    "volume": "11",
    "pages": "2215",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-020-16075-1",
    "image": "images/paper5-toc.png",
    "citation": "Nature Communications 11, 2215 (2020)",
    "doi": "10.1038/s41467-020-16075-1"
  },
  {
    "id": 6,
    "title": "Ultrafast Exciton Transport with a Long Diffusion Length in Layered Perovskites with Organic Cation Functionalization",
    "authors": "X. Xiao, M. Wu, Z. Ni, S. Xu, S. Chen, J. Hu, P. N. Rudd, W. You, J. Huang*",
    "journal": "Advanced Materials",
    "year": 2020,
    "volume": "32",
    "pages": "2004080",
    "abstract": "...",
    "url": "https://onlinelibrary.wiley.com/doi/10.1002/adma.202004080",
    "image": "images/paper6-toc-clear.png",
    "citation": "Advanced Materials 32, 2004080 (2020)",
    "doi": "10.1002/adma.202004080"
  },
  {
    "id": 46,
    "title": "Tunable perovskite-based photodetectors in optical sensing",
    "authors": "J. Wolanyk, X. Xiao, M. Fralaide, N. J. Lauersdorf, R. Kaudal, E. Dykstra, J. Huang*, J. Shinar*, R. Shinar*",
    "journal": "Sensors and Actuators B: Chemical",
    "year": 2020,
    "volume": "321",
    "pages": "128462",
    "abstract": "...",
    "url": "https://www.sciencedirect.com/science/article/pii/S0925400520308078",
    "image": "images/paper46-tunable-photodetectors.png",
    "citation": "Sensors and Actuators B: Chemical 321, 128462 (2020)",
    "doi": "10.1016/j.snb.2020.128462"
  },
  {
    "id": 7,
    "title": "Argon plasma treatment to tune perovskite surface composition for high efficiency solar cells and fast photodetectors",
    "authors": "X. Xiao, C. Bao, Y. Fang, J. Dai, B. Ecker, C. Wang, Y. Lin, S. Tang, Y. Liu, Y. Deng, X. Zheng, Y. Gao, X. C. Zeng, J. Huang*",
    "journal": "Advanced Materials",
    "year": 2018,
    "volume": "30",
    "pages": "1705176",
    "abstract": "...",
    "url": "https://onlinelibrary.wiley.com/doi/10.1002/adma.201705176",
    "image": "images/paper7-argon-plasma.png",
    "citation": "Advanced Materials 30, 1705176 (2018)",
    "doi": "10.1002/adma.201705176"
  },
  {
    "id": 8,
    "title": "Suppressed Ion Migration along the In-Plane Direction in Layered Perovskites",
    "authors": "X. Xiao#, J. Dai#, Y. Fang, J. Zhao, X. Zheng, S. Tang, P. N. Rudd, X. C. Zeng, J. Huang*",
    "journal": "ACS Energy Letters",
    "year": 2018,
    "volume": "3",
    "pages": "684-688",
    "abstract": "...",
    "url": "https://pubs.acs.org/doi/10.1021/acsenergylett.8b00047",
    "image": "images/paper8.png",
    "citation": "ACS Energy Letters 3, 684-688 (2018)",
    "doi": "10.1021/acsenergylett.8b00047"
  },
  {
    "id": 9,
    "title": "Fused-Ring Electron Acceptors as a Versatile Additive Platform for Efficient Perovskite Photovoltaics",
    "authors": "Y. Jiang#, H. Zai#, X. Zheng, Y. Zhang, M. Faheem, S. Dai, Z. Lv, Y. Ma, L. Li, Y. Tao, X. Zhu, J. Kang, S. Liu, H. Lu, S. Qin, T. Song, X. Wang, X. Xiao, H. Yang, X. Lu, Q. Qiao, Q. Chen, H. Zhou*, X. Zhan*",
    "journal": "Journal of the American Chemical Society",
    "year": 2026,
    "volume": "148",
    "pages": "1041-1050",
    "abstract": "...",
    "url": "https://pubs.acs.org/doi/10.1021/jacs.5c16976",
    "image": "images/paper9.jpeg",
    "citation": "Journal of the American Chemical Society 148, 1041-1050 (2026)",
    "doi": "10.1021/jacs.5c16976"
  },
  {
    "id": 10,
    "title": "Enhancing photovoltaic performance by modulating fractal dimensions of non-fullerene acceptors",
    "authors": "X. Zheng, Y. Fu, J. Huang, N. Li, H. Hou, X. Xiao, Y. Lin, X. Lu, X. Zhan*",
    "journal": "Journal of Materials Chemistry C",
    "year": 2026,
    "volume": "14",
    "pages": "3917-3925",
    "abstract": "...",
    "url": "https://pubs.rsc.org/tc/article-abstract/14/10/3917/1244483",
    "image": "images/paper10-toc.png",
    "citation": "Journal of Materials Chemistry C 14, 3917-3925 (2026)",
    "doi": "10.1039/d5tc04292e"
  },
  {
    "id": 11,
    "title": "Improving thermal stability of perovskite solar cells by suppressing ion migration",
    "authors": "Y. Shi, Y. Zheng*, X. Xiao, Y. Li, D. Feng, G. Zhang, Y. Zhang, T. Li, Y. Shao*",
    "journal": "Small Structures",
    "year": 2024,
    "volume": "5",
    "pages": "2400132",
    "abstract": "...",
    "url": "https://onlinelibrary.wiley.com/doi/full/10.1002/sstr.202400132",
    "image": "images/paper11-toc-from-original.png",
    "citation": "Small Structures 5, 2400132 (2024)",
    "doi": "10.1002/sstr.202400132"
  },
  {
    "id": 43,
    "title": "Vertical grain-shape engineering for high-efficiency and stable perovskite solar cells",
    "authors": "Y. Shi, Y. Zheng*, X. Xiao, P. Wang, G. Zhang, Q. Li, G. Zhang, Y. Shao*",
    "journal": "Cell Reports Physical Science",
    "year": 2023,
    "volume": "4",
    "pages": "101649",
    "abstract": "...",
    "url": "https://www.sciencedirect.com/science/article/pii/S2666386423004721",
    "image": "images/paper43-toc-original.png",
    "citation": "Cell Reports Physical Science 4, 101649 (2023)",
    "doi": "10.1016/j.xcrp.2023.101649"
  },
  {
    "id": 12,
    "title": "Defect engineering in wide-bandgap perovskites for efficient perovskite–silicon tandem solar cells",
    "authors": "G. Yang, Z. Ni, Z. J. Yu, B. W. Larson, Z. Yu, B. Chen, A. Alasfour, X. Xiao, J. M. Luther, Z. C. Holman, J. Huang*",
    "journal": "Nature Photonics",
    "year": 2022,
    "volume": "16",
    "pages": "588-594",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41566-022-01033-8",
    "image": "images/paper12.png",
    "citation": "Nature Photonics 16, 588-594 (2022)",
    "doi": "10.1038/s41566-022-01033-8"
  },
  {
    "id": 13,
    "title": "Wireless implantable optical probe for continuous monitoring of oxygen saturation in flaps and organ grafts",
    "authors": "H. Guo#, W. Bai#*, W. Ouyang#, Y. Liu, C. Wu, Y. Xu, Y. Weng, H. Zang, Y. Liu, L. Jacobson, Z. Hu, Y. Wang, H. M. Arafa, Q. Yang, D. Lu, S. Li, L. Zhang, X. Xiao, A. Vázquez-Guardado, J. Ciatti, E. Dempsey, N. Ghoreishi-Haack, E. A. Waters, C. R. Haney, A. M. Westman, M. R. MacEwan, M. A. Pet*, J. A. Rogers*",
    "journal": "Nature Communications",
    "year": 2022,
    "volume": "13",
    "pages": "3009",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-022-30594-z",
    "image": "images/paper13.png",
    "citation": "Nature Communications 13, 3009 (2022)",
    "doi": "10.1038/s41467-022-30594-z"
  },
  {
    "id": 14,
    "title": "Gradient Doping in Sn–Pb Perovskites by Barium Ions for Efficient Single-Junction and Tandem Solar Cells",
    "authors": "Z. Yu, X. Chen, S. P. Harvey, Z. Ni, B. Chen, S. Chen, C. Yao, X. Xiao, S. Xu, G. Yang, Y. Yan, J. J. Berry, M. C. Beard, J. Huang*",
    "journal": "Advanced Materials",
    "year": 2022,
    "volume": "34",
    "pages": "2110351",
    "abstract": "...",
    "url": "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/adma.202110351",
    "image": "images/paper14-toc-clear.png",
    "citation": "Advanced Materials 34, 2110351 (2022)",
    "doi": "10.1002/adma.202110351"
  },
  {
    "id": 44,
    "title": "Constructing Microcavity for Perovskite Laser Power Converter: A Theoretical Study",
    "authors": "G. Ding, Y. Zheng*, Q. Li, G. Zhang, X. Guo, H. Wang, X. Xiao, Y. Feng, Y. Bai*, Y. Shao*",
    "journal": "physica status solidi (a)",
    "year": 2022,
    "volume": "219",
    "pages": "2200539",
    "abstract": "...",
    "url": "https://onlinelibrary.wiley.com/doi/10.1002/pssa.202200539",
    "image": "images/paper44-toc.png",
    "citation": "physica status solidi (a) 219, 2200539 (2022)",
    "doi": "10.1002/pssa.202200539"
  },
  {
    "id": 15,
    "title": "Sustainable development of perovskite solar cells: keeping a balance between toxicity and efficiency",
    "authors": "G. Ding, Y. Zheng, X. Xiao, H. Cheng, G. Zhang, Y. Shi, Y. Shao*",
    "journal": "Journal of Materials Chemistry A",
    "year": 2022,
    "volume": "10",
    "pages": "8159-8171",
    "abstract": "...",
    "url": "https://pubs.rsc.org/ta/article/10/15/8159/789179",
    "image": "images/paper15.png",
    "citation": "Journal of Materials Chemistry A 10, 8159-8171 (2022)",
    "doi": "10.1039/d2ta00248e"
  },
  {
    "id": 16,
    "title": "Recycling lead and transparent conductors from perovskite solar modules",
    "authors": "B. Chen, C. Fei, S. Chen, H. Gu, X. Xiao, J. Huang*",
    "journal": "Nature Communications",
    "year": 2021,
    "volume": "12",
    "pages": "5859",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-021-26121-1",
    "image": "images/paper16.png",
    "citation": "Nature Communications 12, 5859 (2021)",
    "doi": "10.1038/s41467-021-26121-1"
  },
  {
    "id": 17,
    "title": "Heterojunction structures for reduced noise in large-area and sensitive perovskite x-ray detectors",
    "authors": "Y. Zhou, L. Zhao, Z. Ni, S. Xu, J. Zhao, X. Xiao, J. Huang*",
    "journal": "Science Advances",
    "year": 2021,
    "volume": "7",
    "pages": "eabg6716",
    "abstract": "...",
    "url": "https://www.science.org/doi/10.1126/sciadv.abg6716",
    "image": "images/paper17.jpg",
    "citation": "Science Advances 7, eabg6716 (2021)",
    "doi": "10.1126/sciadv.abg6716"
  },
  {
    "id": 45,
    "title": "Strain engineering in metal halide perovskite materials and devices: Influence on stability and optoelectronic properties",
    "authors": "M. Wang, Z. Ni, X. Xiao, Y. Zhou, J. Huang*",
    "journal": "Chemical Physics Reviews",
    "year": 2021,
    "volume": "2",
    "pages": "031302",
    "abstract": "...",
    "url": "https://doi.org/10.1063/5.0044588",
    "image": "images/paper45-figure1-labeled.png",
    "citation": "Chemical Physics Reviews 2, 031302 (2021)",
    "doi": "10.1063/5.0044588"
  },
  {
    "id": 18,
    "title": "Highly efficient pure‐blue light‐emitting diodes based on rubidium and chlorine alloyed metal halide perovskite",
    "authors": "Y. Yang, S. Xu, Z. Ni, C. H. Van Brackle, L. Zhao, X. Xiao, X. Dai, J. Huang*",
    "journal": "Advanced Materials",
    "year": 2021,
    "volume": "33",
    "pages": "2100783",
    "abstract": "...",
    "url": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/adma.202100783",
    "image": "images/paper18-toc.png",
    "citation": "Advanced Materials 33, 2100783 (2021)",
    "doi": "10.1002/adma.202100783"
  },
  {
    "id": 19,
    "title": "Preventing lead leakage with built-in resin layers for sustainable perovskite solar cells",
    "authors": "S. Chen, Y. Deng, X. Xiao, S. Xu, P. N. Rudd, J. Huang*",
    "journal": "Nature Sustainability",
    "year": 2021,
    "volume": "4",
    "pages": "636-643",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41893-021-00701-x",
    "image": "images/paper19-ab.png",
    "citation": "Nature Sustainability 4, 636-643 (2021)",
    "doi": "10.1038/s41893-021-00701-x"
  },
  {
    "id": 20,
    "title": "Defect compensation in formamidinium–caesium perovskites for highly efficient solar mini-modules with improved photostability",
    "authors": "Y. Deng, S. Xu, S. Chen, X. Xiao, J. Zhao, J. Huang*",
    "journal": "Nature Energy",
    "year": 2021,
    "volume": "6",
    "pages": "633-641",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41560-021-00831-8",
    "image": "images/paper20.png",
    "citation": "Nature Energy 6, 633-641 (2021)",
    "doi": "10.1038/s41560-021-00831-8"
  },
  {
    "id": 21,
    "title": "Ligand assisted growth of perovskite single crystals with low defect density",
    "authors": "Y. Liu, X. Zheng, Y. Fang, Y. Zhou, Z. Ni, X. Xiao, S. Chen, J. Huang*",
    "journal": "Nature Communications",
    "year": 2021,
    "volume": "12",
    "pages": "1686",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-021-21934-6",
    "image": "images/paper21.png",
    "citation": "Nature Communications 12, 1686 (2021)",
    "doi": "10.1038/s41467-021-21934-6"
  },
  {
    "id": 22,
    "title": "Iodine reduction for reproducible and  high-performance perovskite solar cells and modules",
    "authors": "S. Chen, X. Xiao, H. Gu, J. Huang*",
    "journal": "Science Advances",
    "year": 2021,
    "volume": "7",
    "pages": "eabe8130",
    "abstract": "...",
    "url": "https://www.science.org/doi/10.1126/sciadv.abe8130",
    "image": "images/paper22-toc.png",
    "citation": "Science Advances 7, eabe8130 (2021)",
    "doi": "10.1126/sciadv.abe8130"
  },
  {
    "id": 23,
    "title": "Crystallization in one-step solution deposition of perovskite films: Upward or downward?",
    "authors": "S. Chen, X. Xiao, B. Chen, L. L. Kelly, J. Zhao, Y. Lin, M. F. Toney, J. Huang*",
    "journal": "Science Advances",
    "year": 2021,
    "volume": "7",
    "pages": "eabb2412",
    "abstract": "...",
    "url": "https://www.science.org/doi/epdf/10.1126/sciadv.abb2412",
    "image": "images/paper23.png",
    "citation": "Science Advances 7, eabb2412 (2021)",
    "doi": "10.1126/sciadv.abb2412"
  },
  {
    "id": 24,
    "title": "Large-area and efficient perovskite light-emitting diodes via low-temperature blade-coating",
    "authors": "S. Chu#, W. Chen#, Z. Fang#, X. Xiao, Y. Liu, J. Chen, J. Huang, Z. Xiao*",
    "journal": "Nature Communications",
    "year": 2021,
    "volume": "12",
    "pages": "147",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-020-20433-4",
    "image": "images/paper24.png",
    "citation": "Nature Communications 12, 147 (2021)",
    "doi": "10.1038/s41467-020-20433-4"
  },
  {
    "id": 25,
    "title": "Metallic surface doping of metal halide perovskites",
    "authors": "Y. Lin, Y. Shao, J. Dai, T. Li, Y. Liu, X. Dai, X. Xiao, Y. Deng, A. Gruverman, X. C. Zeng, J. Huang*",
    "journal": "Nature Communications",
    "year": 2021,
    "volume": "12",
    "pages": "7",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-020-20110-6",
    "image": "images/paper25-toc.png",
    "citation": "Nature Communications 12, 7 (2021)",
    "doi": "10.1038/s41467-020-20110-6"
  },
  {
    "id": 26,
    "title": "Identifying the Soft Nature of Defective Perovskite Surface Layer and Its Removal Using a Facile Mechanical Approach",
    "authors": "S. Chen, Y. Liu, X. Xiao, Z. Yu, Y. Deng, X. Dai, Z. Ni, J. Huang*",
    "journal": "Joule",
    "year": 2020,
    "volume": "4",
    "pages": "2661-2674",
    "abstract": "...",
    "url": "https://www.sciencedirect.com/science/article/pii/S2542435120305031",
    "image": "images/paper26.jpg",
    "citation": "Joule 4, 2661-2674 (2020)",
    "doi": "10.1016/j.joule.2020.10.014"
  },
  {
    "id": 27,
    "title": "Perovskite-filled membranes for flexible and large-area direct-conversion X-ray detector arrays",
    "authors": "J. Zhao, L. Zhao, Y. Deng, X. Xiao, Z. Ni, S. Xu, J. Huang*",
    "journal": "Nature Photonics",
    "year": 2020,
    "volume": "14",
    "pages": "612-617",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41566-020-0678-x",
    "image": "images/paper27-toc.png",
    "citation": "Nature Photonics 14, 612-617 (2020)",
    "doi": "10.1038/s41566-020-0678-x"
  },
  {
    "id": 28,
    "title": "Reduced Self-Doping of Perovskites Induced by Short Annealing for Efficient Solar Modules",
    "authors": "Y. Deng, Z. Ni, A. F. Palmstrom, J. Zhao, S. Xu, C. H. Van Brackle, X. Xiao, K. Zhu*, J. Huang*",
    "journal": "Joule",
    "year": 2020,
    "volume": "4",
    "pages": "1949-1960",
    "abstract": "...",
    "url": "https://www.sciencedirect.com/science/article/pii/S2542435120302877",
    "image": "images/paper28.jpg",
    "citation": "Joule 4, 1949-1960 (2020)",
    "doi": "10.1016/j.joule.2020.07.003"
  },
  {
    "id": 29,
    "title": "Correction to “Tailoring Passivation Molecular Structures for Extremely Small Open-Circuit Voltage Loss in Perovskite Solar Cells”",
    "authors": "S. Yang, J. Dai, Z. Yu, Y. Shao, Y. Zhou, X. Xiao, X. C. Zeng, J. Huang*",
    "journal": "Journal of the American Chemical Society",
    "year": 2020,
    "volume": "142",
    "pages": "11937-11938",
    "abstract": "...",
    "url": "https://pubs.acs.org/doi/10.1021/jacs.0c06421",
    "image": "images/paper29-toc.png",
    "citation": "Journal of the American Chemical Society 142, 11937-11938 (2020)",
    "doi": "10.1021/jacs.0c06421"
  },
  {
    "id": 30,
    "title": "Scalable Fabrication of Efficient Perovskite Solar Modules on Flexible Glass Substrates",
    "authors": "X. Dai, Y. Deng, C. H. Van Brackle, S. Chen, P. N. Rudd, X. Xiao, Y. Lin, B. Chen, J. Huang*",
    "journal": "Advanced Energy Materials",
    "year": 2020,
    "volume": "10",
    "pages": "1903108",
    "abstract": "...",
    "url": "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/aenm.201903108?af=R",
    "image": "images/paper30-toc-clear-noframe.png",
    "citation": "Advanced Energy Materials 10, 1903108 (2020)",
    "doi": "10.1002/aenm.201903108"
  },
  {
    "id": 31,
    "title": "Efficient sky-blue perovskite light-emitting diodes via photoluminescence enhancement",
    "authors": "Q. Wang, X. Wang, Z. Yang, N. Zhou, Y. Deng, J. Zhao, X. Xiao, P. N. Rudd, A. Moran, Y. Yan, J. Huang*",
    "journal": "Nature Communications",
    "year": 2019,
    "volume": "10",
    "pages": "5633",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-019-13580-w",
    "image": "images/paper31-toc.png",
    "citation": "Nature Communications 10, 5633 (2019)",
    "doi": "10.1038/s41467-019-13580-w"
  },
  {
    "id": 32,
    "title": "Enhancing electron diffusion length in narrow-bandgap perovskites for efficient monolithic perovskite tandem solar cells",
    "authors": "Z. Yang, Z. Yu, H. Wei, X. Xiao, Z. Ni, B. Chen, Y. Deng, S. N. Habisreutinger, X. Chen, K. Wang, J. Zhao, P. N. Rudd, J. J. Berry, M. C. Beard, J. Huang*",
    "journal": "Nature Communications",
    "year": 2019,
    "volume": "10",
    "pages": "4498",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-019-12513-x",
    "image": "images/paper32.png",
    "citation": "Nature Communications 10, 4498 (2019)",
    "doi": "10.1038/s41467-019-12513-x"
  },
  {
    "id": 33,
    "title": "Stabilizing halide perovskite surfaces for solar cell operation with wide-bandgap lead oxysalts",
    "authors": "S. Yang, S. Chen, E. Mosconi, Y. Fang, X. Xiao, C. Wang, Y. Zhou, Z. Yu, J. Zhao, Y. Gao, F. De Angelis, J. Huang*",
    "journal": "Science",
    "year": 2019,
    "volume": "365",
    "pages": "473-478",
    "abstract": "...",
    "url": "https://www.science.org/doi/10.1126/science.aax3294",
    "image": "images/paper33-selected.png",
    "citation": "Science 365, 473-478 (2019)",
    "doi": "10.1126/science.aax3294"
  },
  {
    "id": 34,
    "title": "Synthetic control over orientational degeneracy of spacer cations enhances solar cell efficiency in two-dimensional perovskites",
    "authors": "J. Hu, I. W. H. Oswald, S. J. Stuard, M. M. Nahid, N. Zhou, O. F. Williams, Z. Guo, L. Yan, H. Hu, Z. Chen, X. Xiao, Y. Lin, Z. Yang, J. Huang, A. M. Moran, H. Ade, J. R. Neilson, W. You*",
    "journal": "Nature Communications",
    "year": 2019,
    "volume": "10",
    "pages": "1276",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-019-08980-x",
    "image": "images/paper34.png",
    "citation": "Nature Communications 10, 1276 (2019)",
    "doi": "10.1038/s41467-019-08980-x"
  },
  {
    "id": 35,
    "title": "Tailoring Passivation Molecular Structures for Extremely Small Open Circuit Voltage Loss in Perovskite Solar Cells",
    "authors": "S. Yang, J. Dai, Z. Yu, Y. Shao, Y. Zhou, X. Xiao, X. C. Zeng, J. Huang",
    "journal": "Journal of the American Chemical Society",
    "year": 2019,
    "volume": "141",
    "pages": "5781-5787",
    "abstract": "...",
    "url": "https://pubs.acs.org/doi/10.1021/jacs.8b13091",
    "image": "images/paper35.jpeg",
    "citation": "Journal of the American Chemical Society 141, 5781-5787 (2019)",
    "doi": "10.1021/jacs.8b13091"
  },
  {
    "id": 36,
    "title": "Bilateral alkylamine for suppressing charge recombination and improving stability in blade-coated perovskite solar cells",
    "authors": "W.-Q. Wu, Z. Yang, P. N. Rudd, Y. Shao, X. Dai, H. Wei, J. Zhao, Y. Fang, Q. Wang, Y. Liu, Y. Deng, X. Xiao, Y. Feng, J. Huang*",
    "journal": "Science Advances",
    "year": 2019,
    "volume": "5",
    "pages": "eaav8925",
    "abstract": "...",
    "url": "https://www.science.org/doi/10.1126/sciadv.aav8925",
    "image": "images/paper36-panel-ab.png",
    "citation": "Science Advances 5, eaav8925 (2019)",
    "doi": "10.1126/sciadv.aav8925"
  },
  {
    "id": 37,
    "title": "Dual functions of crystallization control and defect passivation enabled by sulfonic zwitterions for stable and efficient perovskite solar cells",
    "authors": "X. Zheng, Y. Deng, B. Chen, H. Wei, X. Xiao, Y. Fang, Y. Lin, Z. Yu, Y. Liu, Q. Wang, J. Huang*",
    "journal": "Advanced Materials",
    "year": 2018,
    "volume": "30",
    "pages": "1803428",
    "abstract": "...",
    "url": "https://advanced.onlinelibrary.wiley.com/doi/abs/10.1002/adma.201803428",
    "image": "images/paper37.jpg",
    "citation": "Advanced Materials 30, 1803428 (2018)",
    "doi": "10.1002/adma.201803428"
  },
  {
    "id": 38,
    "title": "Thin single crystal perovskite solar cells to harvest below-bandgap light absorption",
    "authors": "Z. Chen, Q. Dong, Y. Liu, C. Bao, Y. Fang, Y. Lin, S. Tang, Q. Wang, X. Xiao, Y. Bai, Y. Deng, J. Huang*",
    "journal": "Nature Communications",
    "year": 2017,
    "volume": "8",
    "pages": "1890",
    "abstract": "...",
    "url": "https://www.nature.com/articles/s41467-017-02039-5",
    "image": "images/paper38-thin-single-crystal.png",
    "citation": "Nature Communications 8, 1890 (2017)",
    "doi": "10.1038/s41467-017-02039-5"
  },
  {
    "id": 39,
    "title": "Low-Noise and Large-Linear-Dynamic-Range Photodetectors Based on Hybrid-Perovskite Thin-Single-Crystals",
    "authors": "C. Bao, Z. Chen, Y. Fang, H. Wei, Y. Deng, X. Xiao, L. Li, J. Huang*",
    "journal": "Advanced Materials",
    "year": 2017,
    "volume": "29",
    "pages": "1703209",
    "abstract": "...",
    "url": "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/adma.201703209",
    "image": "images/paper39-low-noise-hd.png",
    "citation": "Advanced Materials 29, 1703209 (2017)",
    "doi": "10.1002/adma.201703209"
  },
  {
    "id": 40,
    "title": "Enhanced Sb2Se3 solar cell performance through theory-guided defect control",
    "authors": "X. Liu, X. Xiao, Y. Yang, D.-J. Xue, D.-B. Li, C. Chen, S. Lu, L. Gao, Y. He, M. C. Beard, G. Wang, S. Chen, J. Tang*",
    "journal": "Progress in Photovoltaics: Research and Applications",
    "year": 2017,
    "volume": "25",
    "pages": "861-870",
    "abstract": "...",
    "url": "https://onlinelibrary.wiley.com/doi/full/10.1002/pip.2900?msockid=375012849d3169713aba03639c57686d",
    "image": "images/paper40.jpg",
    "citation": "Progress in Photovoltaics: Research and Applications 25, 861-870 (2017)",
    "doi": "10.1002/pip.2900"
  }
];
